//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCLTaskApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCLTaskApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed to.
        /// </summary>
        internal static string ChangeOption {
            get {
                return ResourceManager.GetString("ChangeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string CreateOption {
            get {
                return ResourceManager.GetString("CreateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watcher Service.
        /// </summary>
        internal static string FileWatcherService {
            get {
                return ResourceManager.GetString("FileWatcherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System Watcher Service.
        /// </summary>
        internal static string FileWatcherServiceDisplayName {
            get {
                return ResourceManager.GetString("FileWatcherServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watcher Service Host.
        /// </summary>
        internal static string FileWatcherServiceHost {
            get {
                return ResourceManager.GetString("FileWatcherServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked.
        /// </summary>
        internal static string InvokeOption {
            get {
                return ResourceManager.GetString("InvokeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved to.
        /// </summary>
        internal static string MoveOption {
            get {
                return ResourceManager.GetString("MoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pressed.
        /// </summary>
        internal static string PressedKey {
            get {
                return ResourceManager.GetString("PressedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found accordance of rule for file name.
        /// </summary>
        internal static string RuleFoundOption {
            get {
                return ResourceManager.GetString("RuleFoundOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found accordance of rule for file name.
        /// </summary>
        internal static string RuleNotFoundOption {
            get {
                return ResourceManager.GetString("RuleNotFoundOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystemWatcher started monitoring in directories:.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher on path.
        /// </summary>
        internal static string WatcherMessage {
            get {
                return ResourceManager.GetString("WatcherMessage", resourceCulture);
            }
        }
    }
}
